repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      -   id: check-added-large-files
      -   id: check-toml
      -   id: check-yaml
          args: [--unsafe]
      -   id: trailing-whitespace
      -   id: double-quote-string-fixer
      -   id: no-commit-to-branch
          args: [--branch, main, --branch, development]
-   repo: https://github.com/pycqa/flake8
    alias: flake8
    verbose: true
    rev: '4.0.1'
    hooks:
      -   id: flake8
